#!/usr/bin/env python3
"""
Simple Codex generation example that writes a file called `generated_by_codex.py`.
Requires environment variable OPENAI_API_KEY to be set.

This example uses the older "completions" style. Replace `model` with your Codex model
(e.g., "code-davinci-002") or another code-capable model you have access to.
"""
import os
import sys

try:
    import openai
except Exception:
    print("Install the openai package: pip install openai", file=sys.stderr)
    raise

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    print("Please set OPENAI_API_KEY in the environment", file=sys.stderr)
    sys.exit(1)

openai.api_key = OPENAI_API_KEY

# Customize prompt to the code you want Codex to produce
prompt = """# Create a small Python module with a function `thumbnail_from_video`
# that accepts a video path and returns a path to a generated thumbnail image.
# Use moviepy for processing. Include docstrings and a basic CLI.
"""

# Choose a Codex model you have access to (example: "code-davinci-002"). Change as needed.
MODEL = os.environ.get("CODEX_MODEL", "code-davinci-002")

resp = openai.Completion.create(
    engine=MODEL,
    prompt=prompt,
    max_tokens=800,
    temperature=0.2,
    top_p=1.0,
    n=1,
    stop=None,
)

text = resp.choices[0].text
# Some model outputs include leading line breaks
text = text.lstrip("\n")

out_dir = "generated"
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, "generated_by_codex.py")

with open(out_path, "w", encoding="utf-8") as f:
    f.write("# Generated by Codex\n")
    f.write(text)

print(f"Wrote generated code to {out_path}")
